
server:
  #应用启动端口
  port: 8081
  #spring Boot上下文
  servlet:
    context-path: /sptest
#选择要执行的yml文件
spring:
  profiles:
    active: dev

#打印出执行的sql
logging:
  level:
    com.lq.lqproj.dao: debug

#mybatis位置和包配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lq.lqproj.entity
