


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lq?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: lq1992
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    # hikariCP参数
    pool-name: own_hikariCP
    idle-timeout: 180000
    maximum-pool-size: 10
    auto-commit: true
    max-lifetime: 1800000
    connection-timeout: 30000
